from snowflake_connect import get_connection
import warnings
warnings.filterwarnings("ignore")
conn = get_connection(schema="COMMERCE")
cur = conn.cursor()
print("Rebuilding Shopify daily summary...")
cur.execute("DELETE FROM MONARCH_RAW.COMMERCE.SHOPIFY_DAILY_SUMMARY")
cur.execute("""INSERT INTO MONARCH_RAW.COMMERCE.SHOPIFY_DAILY_SUMMARY (summary_date,revenue,net_revenue,units_sold,order_count,aov,new_customers,returning_customers,refunds,discounts) WITH clean_orders AS (SELECT DISTINCT id,DATE(CONVERT_TIMEZONE('America/Denver',raw_data:created_at::TIMESTAMP_TZ)) as order_date,raw_data:total_price::FLOAT as total_price,raw_data:current_total_price::FLOAT as current_price,raw_data:total_discounts::FLOAT as discounts,raw_data:customer:orders_count::INTEGER as orders_count FROM MONARCH_RAW.COMMERCE.SHOPIFY_ORDERS_RAW WHERE raw_data:financial_status::STRING IN ('paid','partially_paid','partially_refunded')),order_units AS (SELECT o.id,DATE(CONVERT_TIMEZONE('America/Denver',o.raw_data:created_at::TIMESTAMP_TZ)) as order_date,SUM(li.value:quantity::INTEGER) as units FROM MONARCH_RAW.COMMERCE.SHOPIFY_ORDERS_RAW o,LATERAL FLATTEN(input=>o.raw_data:line_items) li WHERE o.raw_data:financial_status::STRING IN ('paid','partially_paid','partially_refunded') GROUP BY o.id,order_date) SELECT c.order_date,SUM(c.total_price),SUM(c.current_price),SUM(u.units),COUNT(DISTINCT c.id),CASE WHEN COUNT(DISTINCT c.id)>0 THEN SUM(c.total_price)/COUNT(DISTINCT c.id) ELSE 0 END,SUM(CASE WHEN c.orders_count=1 THEN 1 ELSE 0 END),SUM(CASE WHEN c.orders_count>1 THEN 1 ELSE 0 END),SUM(c.total_price-c.current_price),SUM(c.discounts) FROM clean_orders c JOIN order_units u ON c.id=u.id AND c.order_date=u.order_date GROUP BY c.order_date""")
print("Shopify daily summary done!")
cur.close()
conn.close()
conn = get_connection(schema="COMMERCE")
cur = conn.cursor()
print("Rebuilding Monarch daily summary...")
cur.execute("DELETE FROM MONARCH_RAW.COMMERCE.MONARCH_DAILY_SUMMARY")
cur.execute("""INSERT INTO MONARCH_RAW.COMMERCE.MONARCH_DAILY_SUMMARY (summary_date,total_revenue,shopify_revenue,ad_spend,mer,blended_roas,units_sold,order_count,aov,new_customers,meta_spend,meta_roas,google_spend,google_roas,sessions,conversion_rate) SELECT s.summary_date,s.revenue,s.revenue,COALESCE(SUM(a.spend),0),CASE WHEN COALESCE(SUM(a.spend),0)>0 THEN s.revenue/COALESCE(SUM(a.spend),0) ELSE 0 END,CASE WHEN COALESCE(SUM(a.spend),0)>0 THEN COALESCE(SUM(a.conversion_value),0)/COALESCE(SUM(a.spend),0) ELSE 0 END,s.units_sold,s.order_count,s.aov,s.new_customers,MAX(CASE WHEN a.channel='meta_ads' THEN a.spend ELSE 0 END),MAX(CASE WHEN a.channel='meta_ads' THEN a.roas ELSE 0 END),MAX(CASE WHEN a.channel='google_ads' THEN a.spend ELSE 0 END),MAX(CASE WHEN a.channel='google_ads' THEN a.roas ELSE 0 END),COALESCE(g.sessions,0),CASE WHEN COALESCE(g.sessions,0)>0 THEN s.order_count/g.sessions ELSE 0 END FROM MONARCH_RAW.COMMERCE.SHOPIFY_DAILY_SUMMARY s LEFT JOIN MONARCH_RAW.ADS.DAILY_AD_SUMMARY a ON s.summary_date=a.summary_date LEFT JOIN MONARCH_RAW.COMMERCE.GA4_DAILY_SUMMARY g ON s.summary_date=g.summary_date GROUP BY s.summary_date,s.revenue,s.units_sold,s.order_count,s.aov,s.new_customers,g.sessions""")
cur.execute("SELECT SUM(total_revenue),SUM(units_sold),SUM(order_count),SUM(sessions),MIN(summary_date),MAX(summary_date) FROM MONARCH_RAW.COMMERCE.MONARCH_DAILY_SUMMARY")
row = cur.fetchone()
print(f"Revenue: ${row[0]:,.2f}, Units: {row[1]:,}, Orders: {row[2]:,}, Sessions: {row[3]:,}")
print(f"Range: {row[4]} to {row[5]}")
cur.close()
conn.close()
print("Done!")
